#!/usr/bin/env bash
set -euo pipefail

# scripts/merge-docs.sh
# Conservative merger: builds docs/features/<feature>.md by concatenating provided sources,
# adds provenance top-matter, and moves originals to docs-archived/<feature>/.
#
# RUN AFTER backing up:
# git checkout -b docs/consolidation-$(date +%Y%m%d)
# ./scripts/merge-docs.sh
# git add docs/features docs-archived
# git commit -m "chore(docs): consolidate into docs/features/* and archive originals"
# git push origin HEAD

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUT_DIR="docs/features"
ARCHIVE_DIR="docs-archived"
mkdir -p "$OUT_DIR"
mkdir -p "$ARCHIVE_DIR"

generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
generated_by="docs-consolidation-bot"

# Mapping: each entry is "target|source1;source2;source3"
# (exact mapping produced from your JSON)
map=(
"-captain-showcase---implementation-complete|docs/CAPTAIN_SHOWCASE_READY.md"
"-captain-showcase-feature---visual-guide|docs/CAPTAIN_SHOWCASE_VISUAL_GUIDE.md"
"-captain-showcase-implementation-complete|docs/CAPTAIN_SHOWCASE_SUMMARY.md"
"-main-page-design-upgrade---complete|docs/MAIN_PAGE_UPGRADE_COMPLETE.md"
"-production-readiness-report|docs/PRODUCTION_READY.md"
"30-second-video-trim-implementation-complete|docs/30S_TRIM_IMPLEMENTATION_COMPLETE.md;docs/archive/30S_TRIM_IMPLEMENTATION_COMPLETE.md"
"admin-video-details-feature|docs/ADMIN_VIDEO_DETAILS_FEATURE.md"
"api-cleanup-action-plan|docs/API_CLEANUP_ACTION_PLAN.md;docs/api/API_CLEANUP_ACTION_PLAN.md"
"api-cleanup-progress-summary|docs/API_CLEANUP_PROGRESS.md;docs/archive/API_CLEANUP_PROGRESS.md"
"api-documentation|docs/api/README.md"
"auth-system-cleanup---executive-summary|docs/guides/AUTH_CLEANUP_SUMMARY.md"
"auth-system-cleanup-action-plan|docs/guides/AUTH_CLEANUP_ACTION_PLAN.md"
"authentication-architecture-redesign|docs/guides/AUTH_ARCHITECTURE_REDESIGN.md"
"authentication-cleanup---completion-report|docs/guides/AUTH_CLEANUP_COMPLETE.md"
"authentication-rebuild---critical-fixes-applied|docs/guides/AUTH_REBUILD_FIXES_COMPLETE.md"
"authentication-security-improvements---phase-1-completion-report|docs/guides/AUTH_PHASE_1_COMPLETION_REPORT.md"
"authentication-system---quick-summary|docs/guides/AUTH_IMPROVEMENTS_SUMMARY.md"
"authentication-system-analysis-improvement-proposals|docs/guides/AUTH_SYSTEM_ANALYSIS_AND_IMPROVEMENTS.md"
"authentication-system-issues---executive-summary|docs/guides/AUTH_ISSUES_SUMMARY.md"
"authentication-testing-plan---solution-a|docs/guides/AUTH_TESTING_PLAN.md"
"authentication-updates---zoho-email-integration|docs/guides/ZOHO_EMAIL_UPDATE.md"
"auto-open-trim-modal-implementation-complete|docs/AUTO_TRIM_MODAL_IMPLEMENTATION.md;docs/archive/AUTO_TRIM_MODAL_IMPLEMENTATION.md"
"bug-fixes---post-phase-9-testing|docs/guides/BUG_FIXES_POST_PHASE_9.md"
"captain-showcase---visual-demo-layout-guide|docs/CAPTAIN_SHOWCASE_VISUAL_DEMO.md"
"captain-showcase-section---implementation-complete|docs/CAPTAIN_SHOWCASE_IMPLEMENTATION.md"
"captain-verification-documents---quick-reference|docs/CAPTAIN_VERIFICATION_QUICK_REF.md"
"captain-verification-documents---storage-api-analysis|docs/CAPTAIN_VERIFICATION_DOCUMENTS.md"
"datetime-format-refinement---completed|docs/guides/DATE_FORMAT_REFINEMENT.md"
"datetime-timezone-fix---action-plan|docs/guides/TIMEZONE_FIX_ACTION_PLAN.md"
"datetime-timezone-fix---completed|docs/guides/TIMEZONE_FIX_COMPLETION_REPORT.md"
"debugging-video-dimensions-issue|docs/DEBUG_VIDEO_DIMENSIONS.md"
"deployment-checklist|docs/DEPLOYMENT_CHECKLIST.md"
"deployment-fix-summary|docs/DEPLOYMENT_FIX_SUMMARY.md"
"documentation-reorganization---october-12-2025|docs/archive/DOCUMENTATION_REORGANIZATION_OCT_2025.md"
"email-ui-issues---emergency-fixes-applied|docs/guides/EMAIL_UI_EMERGENCY_FIXES.md"
"email-verification-vs-tac-otp-verification---comparison-analysis|docs/guides/EMAIL_VS_TAC_VERIFICATION.md"
"enhanced-password-management---phase-3a-completion-report|docs/guides/AUTH_PHASE_3A_COMPLETION_REPORT.md"
"external-video-worker-setup-guide|docs/EXTERNAL_WORKER_SETUP.md"
"fishon-captain-register|docs/archive/README_OLD_LEGACY.md"
"fishon-captain-register-documentation|docs/README.md"
"fishon-captain-video-upload-trim-system-refactor-ux-guide|docs/VIDEO_UPLOAD_FIX_GUIDE.md;docs/guides/VIDEO_UPLOAD_FIX_GUIDE.md"
"fix-maximum-update-depth-exceeded-error|docs/FIX_INFINITE_RENDER_LOOP.md;docs/guides/FIX_INFINITE_RENDER_LOOP.md"
"fix-maximum-update-depth-exceeded-error-in-enhancedvideouploader|docs/FIX_ENHANCED_VIDEO_UPLOADER_LOOP.md;docs/guides/FIX_ENHANCED_VIDEO_UPLOADER_LOOP.md"
"fix-portrait-video-upscaling-bug|docs/FIX_PORTRAIT_VIDEO_UPSCALING.md"
"fix-video-dimensions-returning-null|docs/FIX_VIDEO_DIMENSIONS_NULL.md"
"historical-documentation-archive|docs/archive/README.md"
"mfa-api-routes---completion-summary|docs/api/MFA_API_COMPLETION.md"
"mfa-api-routes-reference|docs/api/API_MFA_ROUTES.md"
"mfa-libraries-creation-guide|docs/guides/MFA_LIBRARIES_MANUAL_CREATION.md"
"mfa-nextauth-integration---completion-report|docs/api/MFA_NEXTAUTH_INTEGRATION.md"
"mfa-nextauth-integration---quick-start-guide|docs/api/MFA_QUICKSTART.md"
"mfa-setup---understanding-the-two-step-process|docs/guides/MFA_SETUP_TWO_STEP_PROCESS.md"
"multi-factor-authentication-mfa-implementation|docs/guides/MFA_IMPLEMENTATION.md"
"otptac-implementation-progress|docs/guides/OTP_IMPLEMENTATION_PROGRESS.md"
"otp-verification-flow---implementation-complete|docs/guides/OTP_VERIFICATION_COMPLETE.md"
"otp-verification-ux-improvements---completion-report|docs/guides/OTP_UX_IMPROVEMENTS_COMPLETE.md"
"password-reset-fix---quick-summary|docs/guides/PASSWORD_RESET_FIX_SUMMARY.md"
"password-reset-flow---phase-2-completion-report|docs/guides/AUTH_PHASE_2_COMPLETION_REPORT.md"
"password-reset-hash-issue---resolution|docs/guides/PASSWORD_RESET_HASH_FIX.md"
"password-reset-login-issue---final-fix|docs/guides/PASSWORD_RESET_EMAIL_VERIFICATION_FIX.md"
"pendingmedia-legacy-videouploader-cleanup|docs/PENDINGMEDIA_CLEANUP_README.md;docs/archive/PENDINGMEDIA_CLEANUP_README.md"
"phase-13-migration-deprecation---completion-summary|docs/PHASE_13_COMPLETION_SUMMARY.md;docs/archive/PHASE_13_COMPLETION_SUMMARY.md"
"phase-2a-cleanup-completion-report|docs/PHASE_2A_CLEANUP_COMPLETE.md;docs/archive/PHASE_2A_CLEANUP_COMPLETE.md"
"phase-2b-analysis-worker-endpoint-consolidation|docs/PHASE_2B_WORKER_ANALYSIS.md;docs/archive/PHASE_2B_WORKER_ANALYSIS.md"
"phase-2b-completion-report|docs/PHASE_2B_COMPLETION_REPORT.md;docs/archive/PHASE_2B_COMPLETION_REPORT.md"
"phase-2c-1-completion-report-dual-pipeline-implementation|docs/PHASE_2C_COMPLETION_REPORT.md;docs/archive/PHASE_2C_COMPLETION_REPORT.md"
"phase-2c-migration-plan-blob-upload-video-queue-pipeline|docs/PHASE_2C_MIGRATION_PLAN.md;docs/archive/PHASE_2C_MIGRATION_PLAN.md"
"quick-reference---captain-showcase-feature|docs/CAPTAIN_SHOWCASE_QUICK_REF.md"
"schema-extraction-summary|docs/SCHEMA_EXTRACTION_SUMMARY.md"
"setting-up-mfa-for-oauth-users|docs/guides/MFA_OAUTH_USERS.md"
"solution-a---quick-reference-card|docs/guides/SOLUTION_A_QUICK_REFERENCE.md"
"solution-a-implementation---phase-1-2-complete-|docs/guides/SOLUTION_A_PHASE_1-5_COMPLETE.md"
"solution-a-implementation-complete-summary|docs/guides/SOLUTION_A_IMPLEMENTATION_COMPLETE.md"
"solution-a-implementation-progress---current-status|docs/guides/SOLUTION_A_CURRENT_STATUS.md"
"solution-a-phase-6-completion-report|docs/guides/SOLUTION_A_PHASE_6_COMPLETE.md"
"solution-a-phase-7-completion-report|docs/guides/SOLUTION_A_PHASE_7_COMPLETE.md"
"solution-a-phase-8-completion-report-admin-api-routes|docs/guides/SOLUTION_A_PHASE_8_ADMIN_API_COMPLETE.md"
"solution-a-phase-8-completion-report-admin-security-features|docs/guides/SOLUTION_A_PHASE_8_COMPLETE.md"
"solution-a-rebuild-guide---password-based-mfa-only|docs/guides/SOLUTION_A_REBUILD_GUIDE.md"
"storage-inventory-pagination-fix|docs/STORAGE_PAGINATION_FIX.md"
"storage-inventory-update---new-video-pipeline-support|docs/STORAGE_INVENTORY_UPDATE.md"
"toast-persistence-fix-summary|docs/TOAST_PERSISTENCE_FIX.md;docs/archive/TOAST_PERSISTENCE_FIX.md"
"video-api-routes-documentation|docs/API_VIDEO_ROUTES.md;docs/api/API_VIDEO_ROUTES.md"
"video-dimensions-implementation|docs/VIDEO_DIMENSIONS_IMPLEMENTATION.md"
"video-gallery-fixes---review-step|docs/VIDEO_GALLERY_FIXES.md"
"video-list-api-polling-optimization-plan|docs/VIDEO_LIST_POLLING_OPTIMIZATION.md"
"video-list-polling-optimization---complete-|docs/VIDEO_LIST_POLLING_OPTIMIZATION_COMPLETE.md"
"video-upload-progress-bar-implementation|docs/VIDEO_UPLOAD_PROGRESS_BAR.md"
"video-upload-queue-phase-10---advanced-queue-management-|docs/VIDEO_UPLOAD_PHASE_10_COMPLETION.md;docs/archive/VIDEO_UPLOAD_PHASE_10_COMPLETION.md"
"video-upload-queue-phase-7-8-completion-report|docs/VIDEO_UPLOAD_PHASE_7_8_COMPLETION.md;docs/archive/VIDEO_UPLOAD_PHASE_7_8_COMPLETION.md"
"video-upload-system---phase-status-overview|docs/VIDEO_UPLOAD_PHASES_STATUS.md;docs/archive/VIDEO_UPLOAD_PHASES_STATUS.md"
"video-upload-system-cleanup---october-2025-|docs/VIDEO_UPLOAD_CLEANUP_OCT_2025.md"
"video-upload-system-migration-guide|docs/VIDEO_UPLOAD_MIGRATION.md;docs/archive/VIDEO_UPLOAD_MIGRATION.md"
"video-upload-progress-bar-implementation|docs/VIDEO_UPLOAD_PROGRESS_BAR.md"
"whatsapp-style-video-trim-ui-implementation-complete|docs/WHATSAPP_STYLE_TRIM_UI.md;docs/archive/WHATSAPP_STYLE_TRIM_UI.md"
"z-index-design-system|docs/Z_INDEX_SYSTEM.md;docs/guides/Z_INDEX_SYSTEM.md"
"zoho-email-configuration-guide|docs/guides/ZOHO_EMAIL_CONFIGURATION.md"
)

# iterate mapping
for entry in "${map[@]}"; do
  target="${entry%%|*}"
  srcs="${entry#*|}"
  target_file="${OUT_DIR}/${target}.md"
  echo ">> Building ${target_file}"
  mkdir -p "$(dirname "$target_file")"
  echo "---" > "$target_file"
  echo "generated_by: ${generated_by}" >> "$target_file"
  echo "generated_at: ${generated_at}" >> "$target_file"
  echo "sources:" >> "$target_file"
  IFS=';' read -ra SRC_ARR <<< "$srcs"
  for s in "${SRC_ARR[@]}"; do
    # trim whitespace
    s_trim="$(echo -e "${s}" | sed -e 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    echo "  - ${s_trim}" >> "$target_file"
  done
  echo "---" >> "$target_file"
  echo "" >> "$target_file"
  echo "# ${target}" >> "$target_file"
  echo "" >> "$target_file"
  for s in "${SRC_ARR[@]}"; do
    s_trim="$(echo -e "${s}" | sed -e 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    if [ -f "$s_trim" ]; then
      echo "---- SOURCE: ${s_trim} ----" >> "$target_file"
      echo "" >> "$target_file"
      cat "$s_trim" >> "$target_file"
      echo "" >> "$target_file"
      echo "" >> "$target_file"
      # move to archive preserving relative subpath
      archive_dest="${ARCHIVE_DIR}/${target}/$(basename "$s_trim")"
      mkdir -p "$(dirname "$archive_dest")"
      mv "$s_trim" "$archive_dest"
      echo "  - archived ${s_trim} -> ${archive_dest}"
    else
      echo "---- SOURCE (MISSING): ${s_trim} ----" >> "$target_file"
      echo "" >> "$target_file"
      echo "> NOTE: source file not found at ${s_trim}" >> "$target_file"
      echo "" >> "$target_file"
    fi
  done
  # Add a TODO marker for human review
  echo "" >> "$target_file"
  echo "## TODO: Review & Clean" >> "$target_file"
  echo "- [ ] Remove small duplicated lines / housekeeping." >> "$target_file"
  echo "- [ ] Move anything clearly obsolete into Archive section below." >> "$target_file"
  echo "" >> "$target_file"
  echo "### Archive / Legacy (moved)" >> "$target_file"
  echo "> All originals moved to ${ARCHIVE_DIR}/${target}/" >> "$target_file"
done

echo "Done. Generated files in ${OUT_DIR}, originals archived in ${ARCHIVE_DIR}."